# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4720aa8d076da47219448b211fcff32667d451742ed0c8a7f29d14672cec2ccf0f661afd2064afd0ea1016808103859851a81cad6de598d8448f1194d45f31f7

test:
  secret_key_base: eb4f5a24b4e8e5490ce87a22003ce4c74c7089eeae9d14e986a65a18ea243c44b4672cdc7c5e11f8fa338f1e7f323617b7df1a949970c43133b7aa20e6e5f85c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
